project:
  type: website
  render:
    - index.qmd
    - "/modules/**/*.qmd"

website:
  title: "Test site open ASCAPIM"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - icon: github
        href: https://github.com/rwinsee/site_ascapim
    background: "#008000"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
   - include-code-files